spring:
  # DataSource
  datasource:
    hikari:
      maximum-pool-size: 4
    url: ${BUGBUDDY_DB_URL}?serverTimeZone=Asia/Seoul # jdbc:mysql://localhost:3306/bugbuddy
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${BUGBUDDY_DB_USERNAME}
    password: ${BUGBUDDY_DB_PASSWORD}
  # JPA
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true

